apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
spec:
  template:
  
    metadata:
      name: mypod
      labels:
        env: production
    spec:
      containers:
        - name: nginx-container
          image: nginx

  replicas: 3

  