apiVersion: v1
kind: Service
metadata:
  name: back-end
spec:
  type: ClusterIP
  ports:
    - port: 80 #service-port
      targetPort: 80 #pod-port
  selector:
    app: myapp
    type: back-end
    


  